output_filename: doc.pdf

cover_page: true

include_all_sources: true
# defines the rendering order for the given sources
# if include_all_sources is set to false, only include this sources
sources:
# - source1.md
# - source2.md
#- ...
